pipeline {
    agent any
    tools {
		jdk 'JDK11' 
	}
    stages {
        stage('Récupération des sources') {
            steps {
                git url: 'https://github.com/elanglet/projet-banque.git', branch: 'jenkins'
            }
        }
        stage('Construction du projet') {
            steps {
                dir('banque/') {
                    bat('mvn test package')
                }
            }
        }
        stage('Consolidation des tests') {
            steps {
                junit('**/target/surefire-reports/*.xml')
            }
        }
    }
}
