pipeline {
    agent any
    tools {
		jdk 'JDK11' 
	}
    stages {
        stage('Récupération des sources de l\'application') {
            steps {
                git 'https://github.com/elanglet/projet-banque.git'
            }
        }
        stage('Construction du projet') {
            steps {
                bat('mvn -f banque/pom.xml test package')
            }
        }
        stage('Consolidation des tests') {
            steps {
                junit('**/target/surefire-reports/*.xml')
            }
        }
        stage('Copie du livrable dans le répertoire "docker"') {
        	steps {
        		// bat('dir')
	            bat('copy banque\\banque-web\\target\\banque-web.war docker\\')
	        }
        }
        stage('Création de l\'image Docker') {
           steps {
               bat('docker build -t app-tomcat-web:1.0 docker/')
           }
        }
    }
}
