pipeline {
    agent any
    tools {
		jdk 'JDK11' 
	}
    stages {
        stage('Récupération des sources de l\'application') {
            steps {
                git url:'https://github.com/elanglet/projet-banque.git', branch: 'jenkins'
            }
        }
        stage('Construction du projet') {
            steps {
	            dir('banque') {
	                bat('mvn test package')
	            }
            }
        }
        stage('Copie du livrable dans le répertoire "docker"') {
        	steps {
	           	bat('copy banque\\banque-web\\target\\banque-web.war docker\\')        		 
	        }
        }
        stage('Création de l\'image Docker') {
           steps {
           		bat('docker build -t app-tomcat-web:1.0 docker/')
           }
        }
        stage('Création et démarrage d\'un conteneur') {
            steps {
            	catchError(buildResult: 'SUCCESS', stageResult: 'SUCCESS', message: 'Le conteneur ne semble pas démarré') {
            		bat('docker stop app-srv-test')    
            	}            	
                bat('docker run -d --rm -p9000:8080 --name app-srv-test app-tomcat-web:1.0')
            }
        }
        stage('Récupération des tests Web') {
       		steps {
       			//if(!fileExists('Selenium')) {
                //   bat('md Selenium') 
                //}    
				dir('Selenium') {
				    git url:'https://github.com/elanglet/projet-banque-selenium.git', branch: 'jenkins'
				}
       		}                                 
       	}
       	stage('Exécution des tests Web') {
            steps {
	            dir('Selenium') {
	                bat('mvn -Dwebdriver.chrome.driver=drivers/win/chromedriver.exe -Dwebdriver.gecko.driver=drivers/win/geckodriver.exe test ')
	            }
            }
        }
        stage('Consolidation des tests') {
            steps {
                junit('**/target/surefire-reports/*.xml')
            }
        }
        stage('Arrêt du conteneur') {
            steps {
                bat('docker stop app-srv-test')
            }
        }
    }
}
