pipeline {
    agent any
    tools {
		jdk 'JDK11' 
	}
    stages {
        stage('Récupération des sources de l\'application') {
            steps {
                git url:'https://github.com/elanglet/projet-banque.git', branch: 'jenkins'
            }
        }
        stage('Construction du projet') {
            steps {
	            dir('banque') {
	                bat('mvn test package')
	            }
            }
        }
        stage('Consolidation des tests') {
            steps {
                junit('**/target/surefire-reports/*.xml')
            }
        }
        stage('Copie du livrable dans le répertoire "docker"') {
        	steps {
	           	bat('copy banque\\banque-web\\target\\banque-web.war docker\\')        		 
	        }
        }
        stage('Création de l\'image Docker') {
           steps {
           		bat('docker build -t app-tomcat-web:1.0 docker/')
           }
        }
    }
}
