# Commande : copy /Y .\banque\banque-web\target\banque-web.war .\docker\app

FROM tomcat:9.0.65-jdk11-temurin-focal

# RUN apt update && \
#	apt install curl -y -qq && \
#	curl -u jenkins:jenkins -O http://nexus:8180/repository/maven-snapshots/fr/eni/mvnbook/banque-web/1.0.0-SNAPSHOT/banque-web-1.0.0-20220921.094303-1.war

COPY ./app/banque-web.war /usr/local/tomcat/webapps

